### ISSUE TITLE
The username changing doesn't show

### ISSUE THREAD

**Issue by dariaemacs** [rafalp/Misago#798] opened 2017-04-15 09:10 UTC
The page has this view all the time.

![screenshot from 2017-04-15 12 03 39](https://cloud.githubusercontent.com/assets/22542295/25062394/2fea017e-21d4-11e7-91f1-b2bea7413feb.png)

With this locale:
[ru_locale.zip](https://github.com/rafalp/Misago/files/923458/ru_locale.zip)

**Comment by rafalp** [comment] 2017-04-15 15:43
Potential duplicate of #796.

Still, thanks for including new translation files. I'll test them out myself in reach back. ;)

**Comment by rafalp** [comment] 2017-04-15 16:54
Answered in #796

**Closed** 2017-04-15 16:54 UTC
