### ISSUE TITLE
Facebook connect

### ISSUE THREAD

**Issue by variable** [rafalp/Misago#947] opened 2017-12-29 10:47 UTC
Hello, is Facebook connect feature in the road map?

**Comment by rafalp** [comment] 2017-12-29 17:09
Dupe of #416

**Closed by rafalp** 2017-12-29 17:09 UTC

**Comment by rafalp** [comment] 2018-01-10 13:58
BTW @variable, I've remembered that there's loose roadmap in our readme, at the end of the [Production Use](https://github.com/rafalp/Misago#production-use) section. ;)
