### ISSUE TITLE
user profile posts 404 when user has not post

### ISSUE THREAD

**Issue by ChandlerBent** [rafalp/Misago#1339] opened 2020-06-05 04:07 UTC
It should not display 404 to user when he just register.

misage.core.cursorpagination.py
```
def get_page(queryset, order_by, per_page, start=0, allow_empty=False):
    if start < 0:
        raise InvalidPage()

    object_list = list(_slice_queryset(queryset, order_by, per_page, start))
    if not allow_empty and start and not object_list:
        raise EmptyPage()
```

misago.users.viewmodels.threads.py
``` 
       try:
            list_page = get_page(
                posts_queryset, "-id", request.settings.posts_per_page, start,
                allow_empty=True
            )
        except (EmptyPage, InvalidPage):
            raise Http404()
```

**Comment by JosephWildey** [comment] 2020-06-26 17:22
I'm new to the project but it looks like empty pages are being treated the same as invalid pages. I'd be more than happy to help if you have any idea how this should be addressed instead.

**Comment by JosephWildey** [comment] 2020-06-26 17:35
I'm new to the project. Is there already a default blank user page? If not, that seems more appropriate than treating a blank/empty user page the same as an invalid page. That seems to be the issue here. I can try to work on one if there's not already one in the project.

**Comment by rafalp** [comment] 2020-06-27 00:41
I cannot reproduce this. I can access profile pages for users that haven't posted anything without problem.

**Closed** 2020-06-28 13:31 UTC

**Comment by ChandlerBent** [comment] 2020-06-28 13:32
Sorry, I wrong. I make some mistake.
