### ISSUE TITLE
Subscribe to threads/forums via RSS

### ISSUE THREAD

**Issue by dertuxmalwieder** [rafalp/Misago#537] opened 2015-07-14 09:50 UTC
(Already suggested [here](http://misago-project.org/thread/subscribe-to-threadsforums-per-rss-446/).)

**Comment by rafalp** [comment] 2015-07-14 10:53
dupe of #361

**Closed by rafalp** 2015-07-14 10:53 UTC

**Comment by dertuxmalwieder** [comment] 2015-07-14 10:55
Sorry, my bad.

**Comment by rafalp** [comment] 2015-07-14 10:57
npnp <3
