### ISSUE TITLE
The thread locked after creating of the voting pool in it

### ISSUE THREAD

**Issue by dariaemacs** [rafalp/Misago#797] opened 2017-04-15 08:29 UTC
Why did the thread lock after creating of a pool? 
My user settings: 
- can start own pools
- can edit own pools
- can delete own pools

**I create the theme. It's open for comments:**

![screenshot from 2017-04-15 11 15 01](https://cloud.githubusercontent.com/assets/22542295/25062090/b896d1b6-21cd-11e7-84fd-2f90a4521a9e.png)

**I create the pool in it:**

![screenshot from 2017-04-15 11 15 19](https://cloud.githubusercontent.com/assets/22542295/25062095/d67a6882-21cd-11e7-8197-50cba243fcde.png)

**The thread and the pool becomes closed. And no one can write and get its vote :( **

![screenshot from 2017-04-15 11 15 52](https://cloud.githubusercontent.com/assets/22542295/25062098/eed0546e-21cd-11e7-9948-bd5cfb2b943f.png)

My user settings:

![screenshot from 2017-04-15 11 19 55](https://cloud.githubusercontent.com/assets/22542295/25062107/1d07b75a-21ce-11e7-8b45-a34624e6f862.png)

**Comment by rafalp** [comment] 2017-04-15 15:38
This is potential duplicate of #796, eg. invalid translation crashing javascript that displays actual interactive UI. Can you please provide screenshot of your browser's error console?

**Comment by rafalp** [comment] 2017-04-15 16:54
Answered in #796

**Closed by rafalp** 2017-04-15 16:54 UTC
